### ISSUE TITLE
Changing mode in macOS not working.

### ISSUE THREAD

**Issue by HyungJu** [impankratov/sony-headphones-control-py#2]
I tested this python script with the commit that I made a PR.

If I run the script, the headphone disconnects and make gliched noise. 
then the script terminates.

```shell 
Searching for 38:18:4C:F4:A3:7F...
Connecting to b'38:18:4C:F4:A3:7F' to enable ambient-sound
2020-04-10 23:33:12.361 Python[12075:693941] instantiateOnDevice for regular
```

Thanks

( My environment : macOS Mojave, MBP 15" 2019, WF-1000XM3 )

**Comment by HyungJu** [comment]
ClusterM/sony-headphones-control#5 

There's an related issue in tasker plugin repo.
I think it's an isuue with WF-1000XM3's new firmware.

Is it possible to fix by providing you BT capture of changing the mode from android device?

**Comment by impankratov** [comment]
>Is it possible to fix by providing you BT capture of changing the mode from android device?

Sure, feel free to post your findings here or make PR even. But the main goal is to not break other headphones support (I own WH-H900N so I can test if anything breaks for them).

**Comment by HyungJu** [comment]
Okay! thanks :)
